### ISSUE TITLE
My uploaded 'wp-content' seems to be   ignored

### ISSUE THREAD

**Issue by FredMichel** [struski/tutorial-kubernetes-wordpress#2]
Hello,
Thank you for your tuto. I completed with SSL, however I cannot see "wp-content" I uploaded under /var/www/mysite.com/ when I go to the console admin : https://mysite.com/wp-admin.

I should be able to see my theme and plugins but I can't find them.
 ENV `WPVAR_WP_CONTENT_DIR` is properly initialized in pod :

```
WPVAR_WP_CONTENT_DIR=/var/www/mysite.com/wp-content
```

Thank you for your assistance.

**Comment by struski** [comment]
Please verify that you are using correct **wp-config.php** file. This file is crucial for reading those env vars.

https://github.com/struski/tutorial-kubernetes-wordpress/blob/master/docker/wordpress/wp-config.php

**Comment by FredMichel** [comment]
Hi,
You can close that issue. Problem was related to my misunderstanding of wordpress architecture. Thank you
